filter:
    excluded_paths: [tests/*]
checks:
    php:
        code_rating: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        too_many_arguments: true
        simplify_boolean_return: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        return_doc_comments: true
        require_php_tag_first: true
        require_scope_for_methods: true
        require_scope_for_properties: true
        psr2_class_declaration: true
        property_assignments: true
        properties_in_camelcaps: true
        precedence_mistakes: true
        precedence_in_conditions: true
        php5_style_constructor: true
        parse_doc_comments: true
        parameters_in_camelcaps: true
        parameter_non_unique: false
        parameter_doc_comments: true
        uppercase_constants: true
        remove_extra_empty_lines: true
        no_new_line_at_end_of_file: true
        no_long_variable_names:
            maximum: '25'
        no_goto: true
        function_in_camel_caps: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        avoid_unnecessary_concatenation: true
        avoid_todo_comments: true
        avoid_multiple_statements_on_same_line: true
        align_assignments: true
tools:
    external_code_coverage: true
    php_analyzer: true
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src']
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]